<?php /**
 * Created by PhpStorm.
 * User: filiphristov
 * Date: 17/06/2018
 * Time: 12:18
 */

echo $this->doctype(); ?>

<html>
<head>
	<meta charset="utf-8">
	<title>Agriculture</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/bootstrap-responsive.min.css'?>" type="text/css"/>
	<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/style.css'?>" type="text/css"/>
	<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/bootstrap.min.css'?>" type="text/css"/>

	<script src="<?php echo $this->basePath() . '/js/jquery.min.js'?>" typeof="text/javascript"></script>
	<script src="<?php echo $this->basePath() . '/js/bootstrap.min.js'?>" typeof="text/javascript"></script>
</head>

<body>
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<span class="brand">Agriculture</span>
			<div class="nav-collapse collapse">
				<?php
//					if(!is_null($this->app->curUser())) {
//						echo '
//							<ul class="nav">
//								<li class="active"><a href="#">Home</a></li>
//							</ul>
//						';
//					}
				?>
			</div><!--/.nav-collapse -->
			<div class="logout_container">
				<?php if(!is_null($this->app->curUser())) {
					echo '<a href="' . $this->url('login/process', array('action' => 'logout')) . '">Log out</a>';
				}?>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<?php echo $this->content; ?>
</div> <!-- /container -->
</body>
</html>
