<?php
/**
 * Created by PhpStorm.
 * User: filiphristov
 * Date: 16/06/2018
 * Time: 18:30
 */

namespace Api\Controller;


use Agriculture\ParcelsQuery;
use Agriculture\ProcessedParcels;
use Agriculture\ProcessedParcelsQuery;

class ProcessedController extends AbstractRestfulJsonController
{
	public function getList()
	{
		return parent::getList(); // TODO: Change the autogenerated stub
	}

	public function get($id)
	{
		$processing = ProcessedParcelsQuery::create()
			->filterByParcelId($id)
			->useParcelsQuery()
				->withColumn('PARCELS.PARCEL_NAME', 'ParcelName')
				->withColumn('PARCELS.CULTURE', 'Culture')
			->endUse()
			->useTractorsQuery()
				->withColumn('TRACTORS.TRACTOR_NAME', 'TractorName')
			->endUse()
			->find();

		$info = array(
			array(
				"TotalProcessedArea" => 0,
				"TotalArea" => ParcelsQuery::create()->findPk($id)->getArea()
			)
		);
		foreach ($processing as $parcel) {
			$info[0]["TotalProcessedArea"] += $parcel->getArea();
			array_push($info, $this->data($parcel));
		}

		$result = new \AppResult(200, false, '', $info);
		return $result->render();
	}

	private function data($processing) {
		return array(
			"ParcelName" => $processing->getVirtualColumn("ParcelName"),
			"Culture" => $processing->getVirtualColumn("Culture"),
			"Date" => $processing->getProcessedDate(),
			"TractorName" => $processing->getVirtualColumn("TractorName"),
			"ProcessedArea" => $processing->getArea()
		);
	}

	/**
	 * @param mixed $data {ParcelId, TractorId, ProcessedDate, Area}
	 * @throws \Propel\Runtime\Exception\PropelException
	 */
	public function create($data)
	{
		$parcel = ParcelsQuery::create()->findPk($data["ParcelId"]);

		if($parcel->getArea() < $data["ProcessedArea"]) {
			$result = new \AppResult(409, true, 'Area can\'t be larger then parcel\'s total area.');
			return $result->render();
		}

		$processedParcel = new ProcessedParcels();
		$processedParcel->fromArray($data);
		$processedParcel->save();

		$result = new \AppResult(200, false, 'Successfully created processing', $processedParcel->toArray());
		return $result->render();
	}
}
