--
-- Script to fill in database with sample data
--

INSERT INTO PARCELS (PARCEL_NAME, CULTURE, AREA)
VALUES ('Devision', 'Grassland', 100);

INSERT INTO TRACTORS (TRACTOR_NAME)
VALUES ('Bob');

INSERT INTO PROCESSED_PARCELS (PARCEL_ID, TRACTOR_ID, PROCESSED_DATE, AREA)
VALUES (1, 1, 1529147634466, 60);
