<?php
/**
 * Created by PhpStorm.
 * User: filiphristov
 * Date: 17/06/2018
 * Time: 13:11
 */
?>

<form action="<?php echo $this->url('login/process', array('action' => 'authenticate')) ?>" method="POST">
	<div class="form-group">
		<label for="email">Email address:</label>
		<input type="email" name="email" class="form-control" id="email">
	</div>
	<div class="form-group">
		<label for="pwd">Password:</label>
		<input type="password" name="password" class="form-control" id="pwd">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>
