<?php /**
 * Created by PhpStorm.
 * User: filiphristov
 * Date: 17/06/2018
 * Time: 14:55
 */ ?>

<form id="add-form">
	<div class="form-group">
		<label for="TractorName">Tractor Name:</label>
		<input name="TractorName" class="form-control" id="TractorName">
	</div>
	<button id="addBtn" style="margin-top: 10px" type="submit" class="btn btn-default">Add</button>
</form>

<script>
	$(function () {
		$('#add-form').submit(function (ev) {
			ev.preventDefault();

			var obj = {};
			
			$(this).find('input').each(function () {
				obj[this.id] = this.value;
			});

			$.ajax({
				url: '<?php echo $this->url('api/tractor') ?>',
				type: 'POST',
				data: obj,
				dataType: 'application/json',
				success: function (result) {
					location.pathname = '<?php echo $this->url('app/parcel') ?>';
				},
				error: function(err) {
					console.log(err);
					location.pathname = '<?php echo $this->url('app/parcel') ?>';
				}
			});
		});
	});
</script>
